name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn
          pip install pytest black flake8

      - name: Lint (flake8)
        run: flake8 src tests

      - name: Format check (black)
        run: black --check .

      - name: Run tests
        run: pytest -q
